spring:
  datasource:
    name: rainbow
    url: jdbc:mysql://yuanbaojian.xyz:3306/rain_bow?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT%2B8
    username: rainBow
    password: 312ybj
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: yuanbaojian.xyz
    port: 6379
    password: 312ybj
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0



mybatis-plus:
  type-aliases-package: com.ybj.project.model
  mapper-locations: classpath:com/ybj/project/mapping/*.xml

ybj:
  shiro:
    anonURL: /login,/logout
    en: main


