server:
  port: 8082
spring:
  datasource:
    name: rainbow
    url: jdbc:mysql://yuanbaojian.xyz:3306/rain_bow?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT%2B8
    username: rainBow
    password: 312ybj
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: yuanbaojian.xyz
    port: 6379
    password: root
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

  profiles:
    active: test


mybatis-plus:
  type-aliases-package: com.ybj.project.model
  mapper-locations: classpath:com/atoz/capp/mapping/*.xml


---
#development environment
spring:
  profiles: dev

server:
  port: 8080

my:
  name: ricky

---
#test environment
spring:
  profiles: test

server:
  port: 8088


---
#production environment
spring:
  profiles: prod

server:
  port: 8082


